package view;

import controller.ClienteController;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.PessoaFisica;
import model.PessoaJuridica;

public class TelaConsultaCliente extends javax.swing.JFrame {

    private final ClienteController clienteController;
    private JInternalFrame tela;

    public TelaConsultaCliente(JInternalFrame tela) {
        initComponents();

        this.tela = tela;
        clienteController = new ClienteController();

        DefaultTableModel tabelaClientes = (DefaultTableModel) tableClientes.getModel();
        tabelaClientes.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        tfdNomeCliente = new javax.swing.JTextField();
        btnPesquisarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNomeCliente.setText("Nome do Cliente");

        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF/CNPJ", "Tipo Pessoa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClientes);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lblNomeCliente)
                        .addGap(18, 18, 18)
                        .addComponent(tfdNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisarCliente)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(tfdNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCliente))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(656, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        if ("".equals(tfdNomeCliente.getText())) {
            clienteController.atualizarTabela(tableClientes);
        } else {
            List<Cliente> clientes = clienteController.consultarPorNome(tfdNomeCliente.getText());

            DefaultTableModel tabelaClientes = (DefaultTableModel) tableClientes.getModel();
            tabelaClientes.setRowCount(0);

            for (Cliente cli : clientes) {
                if (cli instanceof PessoaFisica) {
                    tabelaClientes.addRow(new Object[]{
                        cli.getId(),
                        cli.getNome(),
                        ((PessoaFisica) cli).getCpf(),
                        "Pessoa Física"});
                }
                if (cli instanceof PessoaJuridica) {
                    tabelaClientes.addRow(new Object[]{
                        cli.getId(),
                        cli.getNome(),
                        ((PessoaJuridica) cli).getCnpj(),
                        "Pessoa Jurídica"});
                }
            }
            
//            if (cliente != null) {
//                TelaVeiculo telaVeiculo = ((TelaVeiculo) tela);
//                telaVeiculo.getTfdNomeCliente().setText(cliente.getNome());
//                telaVeiculo.getTfdIdCliente().setText(String.valueOf(cliente.getId()));
//
//                if (cliente instanceof PessoaFisica) {
//                    String cpf = ((PessoaFisica) cliente).getCpf();
//                    telaVeiculo.getTfdCpfCnpj().setText(cpf);
//                }
//                if (cliente instanceof PessoaJuridica) {
//                    String cnpj = ((PessoaJuridica) cliente).getCnpj();
//                    telaVeiculo.getTfdCpfCnpj().setText(cnpj);
//                }
//            }
        }
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseClicked
        if (evt.getClickCount() == 2) {

            Integer id = (Integer) tableClientes.getModel().getValueAt(tableClientes.getSelectedRow(), 0);
            String nome = (String) tableClientes.getModel().getValueAt(tableClientes.getSelectedRow(), 1);
            String modelo = (String) tableClientes.getModel().getValueAt(tableClientes.getSelectedRow(), 2);
            String placa = (String) tableClientes.getModel().getValueAt(tableClientes.getSelectedRow(), 3);

//            tfdId.setText(String.valueOf(id));
//            tfdMarca.setText(nome);
//            tfdModelo.setText(modelo);
//            tfdPlaca.setText(placa);
            this.dispose();
        }
    }//GEN-LAST:event_tableClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTextField tfdNomeCliente;
    // End of variables declaration//GEN-END:variables
}
