package view;

import controller.VeiculoController;
import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class TelaVeiculo extends javax.swing.JInternalFrame {

    private final VeiculoController veiculoController;
    
    public TelaVeiculo() {
        initComponents();
        
        DefaultTableModel tabelaVeiculos = (DefaultTableModel) tableVeiculos.getModel();
        tabelaVeiculos.setRowCount(0);
        
        veiculoController = new VeiculoController(this);
    }
    
    private void limparCampos() {
        for (Component c : panel.getComponents()) {
            if (c instanceof JTextField) {
                ((JTextField) c).setText("");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        tfdMarca = new javax.swing.JTextField();
        tfdModelo = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVeiculos = new javax.swing.JTable();
        tfdId = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        lblVagaOcupada = new javax.swing.JLabel();
        tfdPlaca = new javax.swing.JTextField();
        tfdVagaOcupada = new javax.swing.JTextField();
        cbxCor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Gravar alterações");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblId.setText("ID");
        lblId.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblMarca.setText("* Marca");
        lblMarca.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblModelo.setText("* Modelo");
        lblModelo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblCor.setText("* Cor");
        lblCor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        tableVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Modelo", "Placa", "Vaga Ocupada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVeiculos);

        lblPlaca.setText("* Placa");

        lblVagaOcupada.setText("Vaga Ocupada");

        cbxCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amarelo", "Azul", "Branco", "Ciano", "Cinza", "Cinza Claro", "Cinza Escuro", "Laranja", "Magenta", "Preto", "Rosa", "Verde", "Vermelho" }));

        jLabel1.setText("* Campos obrigatórios");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfdModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPlaca, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVagaOcupada, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(42, 42, 42)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(tfdId)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConsultar))
                                    .addComponent(tfdMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(tfdPlaca)
                                    .addComponent(tfdVagaOcupada)
                                    .addComponent(cbxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnIncluir)
                                .addGap(92, 92, 92)
                                .addComponent(btnAlterar)
                                .addGap(97, 97, 97)
                                .addComponent(btnExcluir)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(tfdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(tfdMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(tfdModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(cbxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(tfdPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVagaOcupada)
                    .addComponent(tfdVagaOcupada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
//        veiculoController.consultar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
//        veiculoController.incluir();
//        veiculoController.atualizarTabela();
        limparCampos();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
//        veiculoController.alterar();
//        veiculoController.atualizarTabela();
        limparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
//        veiculoController.excluir();
//        veiculoController.atualizarTabela();
        limparCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tableVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVeiculosMouseClicked
        if(evt.getClickCount() == 2){
            
            
            Integer id = (Integer) tableVeiculos.getModel().getValueAt(tableVeiculos.getSelectedRow(), 0);
            String nome = (String) tableVeiculos.getModel().getValueAt(tableVeiculos.getSelectedRow(), 1);
            String modelo = (String) tableVeiculos.getModel().getValueAt(tableVeiculos.getSelectedRow(), 2);
            String placa = (String) tableVeiculos.getModel().getValueAt(tableVeiculos.getSelectedRow(), 3);

            tfdId.setText(String.valueOf(id));
            tfdMarca.setText(nome);
            tfdModelo.setText(modelo);
            tfdPlaca.setText(placa);
        }
    }//GEN-LAST:event_tableVeiculosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JComboBox<String> cbxCor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblVagaOcupada;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tableVeiculos;
    private javax.swing.JTextField tfdId;
    private javax.swing.JTextField tfdMarca;
    private javax.swing.JTextField tfdModelo;
    private javax.swing.JTextField tfdPlaca;
    private javax.swing.JTextField tfdVagaOcupada;
    // End of variables declaration//GEN-END:variables
    
    public String getTfdMarca() {
        return tfdMarca.getText();
    }

    public void setTfdMarca(String estado) {
        this.tfdMarca.setText(estado);
    }

    public String getTfdId() {
        return tfdId.getText();
    }

    public void setTfdId(String id) {
        this.tfdId.setText(id);
    }

    public String getTfdModelo() {
        return tfdModelo.getText();
    }

    public void setTfdModelo(String modelo) {
        this.tfdModelo.setText(modelo);
    }

    public String getTfdPlaca() {
        return tfdPlaca.getText();
    }

    public void setTfdPlaca(String placa) {
        this.tfdPlaca.setText(placa);
    }
    
    public String getTfdVagaOcupada() {
        return tfdVagaOcupada.getText();
    }

    public void setTfdVagaOcupada(String placa) {
        this.tfdVagaOcupada.setText(placa);
    }

    public JTable getTableVeiculos() {
        return tableVeiculos;
    }

    public JPanel getPanel() {
        return panel;
    }

    public JComboBox<String> getCbxCor() {
        return cbxCor;
    }

    public void setCbxCor(JComboBox<String> cbxCor) {
        this.cbxCor = cbxCor;
    }

}
