package view;

import controller.ClienteController;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class TelaCliente extends javax.swing.JInternalFrame {

    private final ClienteController clienteController;
    
    public TelaCliente() {
        initComponents();

        clienteController = new ClienteController(this);

        DefaultTableModel tabelaClientes = (DefaultTableModel) tableClientes.getModel();
        tabelaClientes.setRowCount(0);

        alterarEstadoBotoes(false, true, false, false);
        estadoTelaInclusao(false);
    }

    private void alterarEstadoBotoes(boolean incluir, boolean consultar, boolean alterar, boolean excluir) {
        btnIncluir.setEnabled(incluir);
        btnConsultar.setEnabled(consultar);
        btnExcluir.setEnabled(excluir);
        btnAlterar.setEnabled(alterar);
    }

    private void estadoTelaInclusao(boolean inclusao) {
        tfdId.setEnabled(!inclusao);
        
        tfdBairro.setEnabled(inclusao);
        tfdCep.setEnabled(inclusao);
        tfdComplemento.setEnabled(inclusao);
        tfdCpfCnpj.setEnabled(inclusao);
        tfdLogradouro.setEnabled(inclusao);
        tfdNome.setEnabled(inclusao);
        tfdNomeFantasia.setEnabled(inclusao);
        tfdNumero.setEnabled(inclusao);
        tfdTelCelular.setEnabled(inclusao);
        tfdTelComercial.setEnabled(inclusao);
        tfdTelFixo.setEnabled(inclusao);
        rbtPessoaFisica.setEnabled(inclusao);
        rbtPessoaJuridica.setEnabled(inclusao);
        
        panelEndResidencial.setEnabled(inclusao);
        cbxMunicipio.setEnabled(inclusao);
    }

    private void limparCampos() {
        tfdBairro.setText("");
        tfdCep.setText("");
        tfdComplemento.setText("");
        tfdCpfCnpj.setText("");
        tfdId.setText("");
        tfdLogradouro.setText("");
        tfdNome.setText("");
        tfdNomeFantasia.setText("");
        tfdNumero.setText("");
        tfdTelCelular.setText("");
        tfdTelComercial.setText("");
        tfdTelFixo.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipoCliente = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCliente = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        tfdId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        tfdCpfCnpj = new javax.swing.JTextField();
        lblTelFixo = new javax.swing.JLabel();
        tfdTelFixo = new javax.swing.JTextField();
        lblTelCelular = new javax.swing.JLabel();
        tfdTelCelular = new javax.swing.JTextField();
        lblTelComercial = new javax.swing.JLabel();
        tfdTelComercial = new javax.swing.JTextField();
        rbtPessoaFisica = new javax.swing.JRadioButton();
        rbtPessoaJuridica = new javax.swing.JRadioButton();
        lblTipoCliente = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        lblNomeFantasia = new javax.swing.JLabel();
        tfdNomeFantasia = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnVeiculos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        lblTableClientes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelEndResidencial = new javax.swing.JPanel();
        lblLogradouro = new javax.swing.JLabel();
        tfdLogradouro = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        tfdNumero = new javax.swing.JTextField();
        tfdBairro = new javax.swing.JTextField();
        tfdComplemento = new javax.swing.JTextField();
        tfdCep = new javax.swing.JTextField();
        cbxMunicipio = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Clientes");
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblId.setText("ID do cliente:");

        lblNome.setText("* Nome:");

        lblCpf.setText("* CPF/CNPJ:");

        lblTelFixo.setText("Telefone Fixo:");

        lblTelCelular.setText("Telefone Celular:");

        lblTelComercial.setText("Telefone Comercial:");

        btgTipoCliente.add(rbtPessoaFisica);
        rbtPessoaFisica.setText("Pessoa Física");

        btgTipoCliente.add(rbtPessoaJuridica);
        rbtPessoaJuridica.setText("Pessoa Jurídica");

        lblTipoCliente.setText("* Tipo de Cliente:");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblNomeFantasia.setText("Nome Fantasia:");

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Gravar alterações");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnVeiculos.setText("Veículos");

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF/CNPJ", "Tipo de Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClientes);

        lblTableClientes.setText("Clientes cadastrados");

        jLabel1.setText("* Campos obrigatórios");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelClienteLayout.createSequentialGroup()
                                    .addComponent(lblId)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfdId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnConsultar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNovo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteLayout.createSequentialGroup()
                                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfdNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTableClientes)
                                            .addComponent(jLabel1)
                                            .addGroup(panelClienteLayout.createSequentialGroup()
                                                .addComponent(lblTipoCliente)
                                                .addGap(27, 27, 27)
                                                .addComponent(rbtPessoaFisica)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbtPessoaJuridica))
                                            .addGroup(panelClienteLayout.createSequentialGroup()
                                                .addComponent(lblNome)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(btnAlterar)
                                .addGap(37, 37, 37)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(122, 122, 122))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addGap(18, 18, 18)
                                .addComponent(tfdCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(lblTelCelular)
                                .addGap(18, 18, 18)
                                .addComponent(tfdTelCelular))
                            .addComponent(lblNomeFantasia))
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblTelComercial))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTelFixo)))
                        .addGap(18, 18, 18)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdTelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnConsultar, btnNovo});

        panelClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnIncluir});

        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(tfdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar)
                    .addComponent(btnNovo))
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVeiculos))
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtPessoaFisica)
                    .addComponent(rbtPessoaJuridica)
                    .addComponent(lblTipoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFantasia)
                    .addComponent(tfdNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelFixo)
                        .addComponent(tfdTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCpf)))
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdTelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelCelular)
                        .addComponent(tfdTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelComercial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnIncluir)
                    .addComponent(btnCancelar))
                .addGap(27, 27, 27)
                .addComponent(lblTableClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Cadastrais", panelCliente);

        lblLogradouro.setText("Logradouro");

        lblNumero.setText("Número");

        lblBairro.setText("Bairro");

        lblMunicipio.setText("Município");

        lblComplemento.setText("Complemento");

        lblCep.setText("CEP");

        javax.swing.GroupLayout panelEndResidencialLayout = new javax.swing.GroupLayout(panelEndResidencial);
        panelEndResidencial.setLayout(panelEndResidencialLayout);
        panelEndResidencialLayout.setHorizontalGroup(
            panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEndResidencialLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEndResidencialLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEndResidencialLayout.createSequentialGroup()
                                .addComponent(lblMunicipio)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEndResidencialLayout.createSequentialGroup()
                                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLogradouro)
                                    .addComponent(lblNumero)
                                    .addComponent(lblBairro))
                                .addGap(18, 18, 18)
                                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfdLogradouro)
                                    .addComponent(tfdNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(203, 203, 203))
                    .addGroup(panelEndResidencialLayout.createSequentialGroup()
                        .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblComplemento)
                            .addComponent(lblCep))
                        .addGap(18, 18, 18)
                        .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdComplemento)
                            .addComponent(tfdCep, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelEndResidencialLayout.setVerticalGroup(
            panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEndResidencialLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogradouro)
                    .addComponent(tfdLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(tfdNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(tfdBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMunicipio)
                    .addComponent(cbxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(tfdComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEndResidencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(tfdCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Endereço", panelEndResidencial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        if(clienteController.incluir()){
            clienteController.atualizarTabela();
            limparCampos();
            estadoTelaInclusao(false);
            alterarEstadoBotoes(false, true, false, false);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        clienteController.excluir();
        clienteController.atualizarTabela();
        limparCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
//        clienteController.alterar();
        clienteController.atualizarTabela();
        limparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (clienteController.consultar(tfdId.getText())) {
            tfdId.setEnabled(false);
            alterarEstadoBotoes(false, false, true, true);
            estadoTelaInclusao(true);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        alterarEstadoBotoes(true, false, false, false);
        estadoTelaInclusao(true);
        clienteController.atualizarMunicipios();
        limparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        alterarEstadoBotoes(false, true, false, false);
        estadoTelaInclusao(false);
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseClicked
        if(evt.getClickCount() == 2){
            Integer id = (Integer) tableClientes.getModel().getValueAt(tableClientes.getSelectedRow(), 0);
            clienteController.consultar(String.valueOf(id));
            tfdId.setText(String.valueOf(id));
            alterarEstadoBotoes(false, false, true, true);
            estadoTelaInclusao(true);
        }
    }//GEN-LAST:event_tableClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipoCliente;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVeiculos;
    private javax.swing.JComboBox<String> cbxMunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTableClientes;
    private javax.swing.JLabel lblTelCelular;
    private javax.swing.JLabel lblTelComercial;
    private javax.swing.JLabel lblTelFixo;
    private javax.swing.JLabel lblTipoCliente;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelEndResidencial;
    private javax.swing.JRadioButton rbtPessoaFisica;
    private javax.swing.JRadioButton rbtPessoaJuridica;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTextField tfdBairro;
    private javax.swing.JTextField tfdCep;
    private javax.swing.JTextField tfdComplemento;
    private javax.swing.JTextField tfdCpfCnpj;
    private javax.swing.JTextField tfdId;
    private javax.swing.JTextField tfdLogradouro;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdNomeFantasia;
    private javax.swing.JTextField tfdNumero;
    private javax.swing.JTextField tfdTelCelular;
    private javax.swing.JTextField tfdTelComercial;
    private javax.swing.JTextField tfdTelFixo;
    // End of variables declaration//GEN-END:variables

    public JRadioButton getRbtPessoaFisica() {
        return rbtPessoaFisica;
    }

    public void setRbtPessoaFisica(JRadioButton rbtPessoaFisica) {
        this.rbtPessoaFisica = rbtPessoaFisica;
    }

    public JTable getTableClientes() {
        return tableClientes;
    }

    public void setTableClientes(JTable tableClientes) {
        this.tableClientes = tableClientes;
    }

    public JTextField getTfdCpfCnpj() {
        return tfdCpfCnpj;
    }

    public void setTfdCpfCnpj(JTextField tfdCpfCnpj) {
        this.tfdCpfCnpj = tfdCpfCnpj;
    }

    public JTextField getTfdId() {
        return tfdId;
    }

    public void setTfdId(JTextField tfdId) {
        this.tfdId = tfdId;
    }

    public JTextField getTfdNome() {
        return tfdNome;
    }

    public void setTfdNome(JTextField tfdNome) {
        this.tfdNome = tfdNome;
    }

    public JTextField getTfdNomeFantasia() {
        return tfdNomeFantasia;
    }

    public void setTfdNomeFantasia(JTextField tfdNomeFantasia) {
        this.tfdNomeFantasia = tfdNomeFantasia;
    }

    public JTextField getTfdTelCelular() {
        return tfdTelCelular;
    }

    public void setTfdTelCelular(JTextField tfdTelCelular) {
        this.tfdTelCelular = tfdTelCelular;
    }

    public JTextField getTfdTelComercial() {
        return tfdTelComercial;
    }

    public void setTfdTelComercial(JTextField tfdTelComercial) {
        this.tfdTelComercial = tfdTelComercial;
    }

    public JTextField getTfdTelFixo() {
        return tfdTelFixo;
    }

    public void setTfdTelFixo(JTextField tfdTelFixo) {
        this.tfdTelFixo = tfdTelFixo;
    }

    public JRadioButton getRbtPessoaJuridica() {
        return rbtPessoaJuridica;
    }

    public void setRbtPessoaJuridica(JRadioButton rbtPessoaJuridica) {
        this.rbtPessoaJuridica = rbtPessoaJuridica;
    }

    public JComboBox<String> getCbxMunicipio() {
        return cbxMunicipio;
    }

    public void setCbxMunicipio(JComboBox<String> cbxMunicipio) {
        this.cbxMunicipio = cbxMunicipio;
    }

    public JTextField getTfdBairro() {
        return tfdBairro;
    }

    public void setTfdBairro(JTextField tfdBairro) {
        this.tfdBairro = tfdBairro;
    }

    public JTextField getTfdCep() {
        return tfdCep;
    }

    public void setTfdCep(JTextField tfdCep) {
        this.tfdCep = tfdCep;
    }

    public JTextField getTfdComplemento() {
        return tfdComplemento;
    }

    public void setTfdComplemento(JTextField tfdComplemento) {
        this.tfdComplemento = tfdComplemento;
    }

    public JTextField getTfdLogradouro() {
        return tfdLogradouro;
    }

    public void setTfdLogradouro(JTextField tfdLogradouro) {
        this.tfdLogradouro = tfdLogradouro;
    }

    public JTextField getTfdNumero() {
        return tfdNumero;
    }

    public void setTfdNumero(JTextField tfdNumero) {
        this.tfdNumero = tfdNumero;
    }

    
}
